# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Magma to NPM

on:
  push:
    branches:
      - main
      - release/*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build --if-present
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}


      - name: Successful Deployment Notification
        if: success() && !contains(github.event.head_commit.message, '[no-notify]')
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "🚀 Successful Deployment of Magma Framework",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n`${{ github.sha }}`"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Author:*\n${{ github.actor }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Changes:*\n${{ github.event.head_commit.message }}"
                  }
                ]
              }
              ]
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
